### ISSUE TITLE
ValueError: ssh2.sftp.SFTP has the wrong size, try recompiling. Expected 20, got 16

### ISSUE THREAD

**Issue by vladimirf7** [ParallelSSH/parallel-ssh#113]
### Bug reports

__Steps to reproduce:__

1. `pip install parallel-ssh`
1. Start python and try to import `from pssh.pssh2_client import ParallelSSHClient`

__Expected behaviour:__ Successful import

__Actual behaviour:__ 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\env\lib\site-packages\pssh\pssh2_client.py", line 23, in <module>
    from .ssh2_client import SSHClient
  File "...\env\lib\site-packages\pssh\ssh2_client.py", line 42, in <module>
    from .native._ssh2 import wait_select, _read_output  # , sftp_get, sftp_put
  File "env/local/lib/python2.7/site-packages/ssh2/sftp.pxd", line 26, in init pssh.native._ssh2
ValueError: ssh2.sftp.SFTP has the wrong size, try recompiling. Expected 20, got 16
```

__Additional info:__
```
(env) λ pip freeze
asn1crypto==0.24.0
cffi==1.11.5
cryptography==2.2.2
gevent==1.2.2
greenlet==0.4.13
idna==2.6
parallel-ssh==1.5.2
paramiko==2.1.5
pyasn1==0.4.2
pycparser==2.18
six==1.11.0
ssh2-python==0.11.0

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the report. What is the version of `parallel-ssh` and `ssh2-python` used? This shows up on latest master versions due to bad release but should not affect released versions.
