### ISSUE TITLE
ssh2.exceptions.ChannelRequestDenied when forwarding ssh agent

### ISSUE THREAD

**Issue by teucrus** [ParallelSSH/parallel-ssh#142]
I am getting the error below when I try to run the code below on a mikrotik routerOS router.
Am I doing something wrong?
My code:

```
from pssh.clients.native import ParallelSSHClient

connection=ParallelSSHClient(['x.x.x.x'],'user','pass')
out=connection.run_command('log print')

```
The error i get:

```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\ndbot\test.py", line 4, in <module>
    out=connection.run_command('log print')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 220, in run_command
    greenlet_timeout=greenlet_timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\base_pssh.py", line 96, in run_command
    self.get_output(cmd, output, timeout=greenlet_timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\base_pssh.py", line 141, in get_output
    (channel, host, stdout, stderr, stdin) = cmd.get(timeout=timeout)
  File "src\gevent\greenlet.py", line 659, in gevent._greenlet.Greenlet.get
  File "src\gevent\greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 234, in _run_command
    raise ex
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 230, in _run_command
    use_pty=use_pty, encoding=encoding, timeout=timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 417, in run_command
    channel = self.execute(_command, use_pty=use_pty)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 299, in execute
    channel = self.open_session() if channel is None else channel
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 284, in open_session
    self._eagain(chan.request_auth_agent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 357, in _eagain
    ret = func(*args, **kwargs)
  File "ssh2\channel.pyx", line 475, in ssh2.channel.Channel.request_auth_agent
  File "ssh2\utils.pyx", line 139, in ssh2.utils.handle_error_codes
ssh2.exceptions.ChannelRequestDenied
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

It means the underlying client library did not succeed in forwarding an SSH agent to that server (exception from `ssh2.channel.Channel.request_auth_agent`). Not all servers follow the SSH specification so what features work will vary across server implementations. There is no guarantee that the library will work as expected on non-standard server implementations.

Try with `ParallelSSHClient(<..>, forward_ssh_agent=False)` to disable agent forwarding.

**Comment by teucrus** [comment]
Tried this:
```
from pssh.clients.native import ParallelSSHClient

connection=ParallelSSHClient(['x.x.x.x'],'user','pass', forward_ssh_agent=False)
out=connection.run_command('log print')
```

Still getting error:

```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\ndbotpssh\ndbot.py", line 17, in <module>
    identity=connection.run_command('log print')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 220, in run_command
    greenlet_timeout=greenlet_timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\base_pssh.py", line 96, in run_command
    self.get_output(cmd, output, timeout=greenlet_timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\base_pssh.py", line 141, in get_output
    (channel, host, stdout, stderr, stdin) = cmd.get(timeout=timeout)
  File "src\gevent\greenlet.py", line 659, in gevent._greenlet.Greenlet.get
  File "src\gevent\greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 234, in _run_command
    raise ex
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\parallel.py", line 230, in _run_command
    use_pty=use_pty, encoding=encoding, timeout=timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 417, in run_command
    channel = self.execute(_command, use_pty=use_pty)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 299, in execute
    channel = self.open_session() if channel is None else channel
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 284, in open_session
    self._eagain(chan.request_auth_agent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pssh\clients\native\single.py", line 357, in _eagain
    ret = func(*args, **kwargs)
  File "ssh2\channel.pyx", line 475, in ssh2.channel.Channel.request_auth_agent
  File "ssh2\utils.pyx", line 139, in ssh2.utils.handle_error_codes
ssh2.exceptions.ChannelRequestDenied
```

**Comment by teucrus** [comment]
I just wanted to add that I already have a prokect that is running with Fabric which is running using paramiko and it works very well. I just wanted to test parallel-ssh to see if it can give me a bit more performance.

If you wish, I can assist by providing access to such a device so you can reproduce the issue. Of cource you can also set it up yourself by running an image via virtualbox or other virtual machine.

If you search for mikrotik CHR. It's free to test.

**Comment by pkittenis** [comment]
There is a bug in the native client in not being able to turn off agent forwarding.

If you know paramiko works for the device the paramiko client in `parallel-ssh` can be used:

```
from pssh.clients.miko import ParallelSSHClient
```

This client has higher performance than fabric by orders of magnitude even using the same paramiko client, but the native client is another order of magnitude faster than paramiko. See [benchmarks](https://parallel-ssh.org/post/parallel-ssh-libssh2/).

**Comment by teucrus** [comment]
Yes, I read the benchmark, that's why I tried to switch. But if I am going to use paramiko, for now I will stay with fabric until the native client issue is fixed.

**Comment by teucrus** [comment]
Yes, I read the benchmark, that's why I tried to switch. But if I am going to use paramiko, for now I will stay with fabric until the native client issue is fixed.

**Comment by pkittenis** [comment]
Up to you. Just keep in mind the paramiko client in parallel-ssh is faster than fabric, just not as much as the native one. How much faster depends on number of hosts and concurrency - fabric starts to slow down dramatically at >= 10 hosts or so.

**Comment by teucrus** [comment]
Hello,
Your latest update fixed the issue.
Now I can succesfully run my script.
Thank you.

**Comment by pkittenis** [comment]
Glad to hear that, thanks for confirming. 

Have also raised #144 to disable agent forwarding in the native client while it is not supported by upstream for future releases.
