### ISSUE TITLE
How to specify the equivalent of "StrictHostKeyChecking no"?

### ISSUE THREAD

**Issue by borice** [ParallelSSH/parallel-ssh#181]
### Bug reports

__Steps to reproduce:__

1. Example code that produces error.
```
import sys
from pprint import pprint
from pssh.clients.native import ParallelSSHClient
from pssh.utils import enable_host_logger

hosts_file = sys.argv[1]

with open(hosts_file, 'r') as hf:
    hosts = [ host.rstrip() for host in hf.readlines() ]

print("Hosts: {}".format(hosts))

client = ParallelSSHClient(hosts)

enable_host_logger()

output = client.run_command('uname -a')
client.join(output, consume_output=True)
```

2. Stack trace or error messages.

__Expected behaviour:__ [What was expected to happen.]
Expected that the code worked as intended... the command executed on all hosts.

__Actual behaviour:__ [What actually happened.]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pssh/clients/native/single.py", line 182, in _init
    self.session.handshake(self.sock)
  File "ssh2/session.pyx", line 81, in ssh2.session.Session.handshake
  File "ssh2/utils.pyx", line 111, in ssh2.utils.handle_error_codes
ssh2.exceptions.KeyExchangeError
```
__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]
```
parallel-ssh    1.9.1
paramiko        2.6.0
ssh2-python     0.18.0.post1
```

It seems that the `/etc/ssh/ssh_config` file is ignored when using the above code. Here are the relevant parts of `/etc/ssh/ssh_config` file on these hosts:
```
Host *
ForwardX11Trusted yes
Protocol 2
StrictHostKeyChecking no
Port 203
```

I know that I can specify use of port 203 via `port=203` constructor argument to `ParallelSSHClient`, but I don't know how to specify the equivalent of `StrictHostKeyChecking no` which I suspect is why the above `ssh2.exceptions.KeyExchangeError` happens.

I also discovered that there is a `pssh.utils.read_openssh_config` but I don't know how to use this in the context of `ParallelSSHClient`.

Please help.

**Comment by borice** [comment]
Based on further research I am no longer convinced that the `StrictHostKeyChecking` setting is at fault for the exception. I manually forced `StrictHostKeyChecking=yes` via
```
ssh -o StrictHostKeyChecking=yes <host>
``
and that connection worked fine.

I should note that I am able to `ssh <host>` from the shell just fine, without being prompted for username/password, based only on the `/etc/ssh/ssh_config`.  I don't have a `~/.ssh/config` and the private key is the default `id_rsa` from `~/.ssh/id_rsa`.

Here's an example `ssh -v <host>` output:
```
capitanu@nid00900:~> ssh -v nid00901
OpenSSH_6.2p2, OpenSSL 0.9.8j-fips 07 Jan 2009
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 25: Applying options for *
debug1: Connecting to nid00901 [10.128.3.140] port 203.
debug1: Connection established.
debug1: identity file /u/capitanu/.ssh/id_rsa type 1
debug1: identity file /u/capitanu/.ssh/id_rsa-cert type -1
debug1: identity file /u/capitanu/.ssh/id_dsa type 2
debug1: identity file /u/capitanu/.ssh/id_dsa-cert type -1
debug1: identity file /u/capitanu/.ssh/id_ecdsa type 3
debug1: identity file /u/capitanu/.ssh/id_ecdsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.2
debug1: match: OpenSSH_6.2 pat OpenSSH*
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 51:8d:e5:85:3d:db:d3:fd:98:23:e6:0a:a8:21:25:ce [MD5]
debug1: Host '[nid00901]:203' is known and matches the ECDSA host key.
debug1: Found key in /u/capitanu/.ssh/known_hosts:59
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /u/capitanu/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: read PEM private key done: type RSA
debug1: Authentication succeeded (publickey).
Authenticated to nid00901 ([10.128.3.140]:203).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LC_ALL = POSIX
debug1: Sending env LANG = en_US.UTF-8
Last login: Thu Sep 26 12:57:11 2019 from nid00900
...
```

**Comment by borice** [comment]
Not sure what's going on -- I was using Python 3.6.6
I upgraded to Python 3.7.2 and the code works as posted.

`pip3 --list` includes:
```
parallel-ssh    1.9.1
paramiko        2.6.0
ssh2-python     0.18.0.post1
```

so the versions are the same as before.

Anyway - closing this as it doesn't seem to be an issue in this library.
