### ISSUE TITLE
OSError: [Errno 24] Too many open files when copying a large set

### ISSUE THREAD

**Issue by dyasny** [ParallelSSH/parallel-ssh#195]
I have a few k files I need to push in small sets (9 files per iteration) to a set of hosts. I bundle a list of 9 the files with a list of nodes to copy to, and iterate over the files each time, passing the file path to the function below. 

After a few iterations (20), I get the traceback below. I suspect after the copy, the fd isn't getting closed

### Bug reports

__Steps to reproduce:__

1. Example code that produces error.
2. Stack trace or error messages.

```python
def copy_file(file_path, node_list, dest_dir, **kwargs):
    success = True
    client = ParallelSSHClient(node_list,**kwargs)
    filename = file_path.split('/')[-1]
    greenlets = client.copy_file(file_path, dest_dir + '/' + filename)
    out = joinall(greenlets, raise_error=True)
    for item in out:
        if not item.successful():
            success = False
    return success
```

Traceback:
```
<ipython-input-87-004130288fe2> in copy_file(file_path, node_list, dest_dir, **kwargs)
    367     filename = file_path.split('/')[-1]
    368     greenlets = client.copy_file(file_path, dest_dir + '/' + filename)
--> 369     out = joinall(greenlets, raise_error=True)
    370     for item in out:
    371         if not item.successful():

~/.local/lib/python3.6/site-packages/gevent/_greenlet.cpython-36m-x86_64-linux-gnu.so in gevent._greenlet.joinall()

~/.local/lib/python3.6/site-packages/gevent/_greenlet.cpython-36m-x86_64-linux-gnu.so in gevent._greenlet.joinall()

~/.local/lib/python3.6/site-packages/gevent/_greenlet.cpython-36m-x86_64-linux-gnu.so in gevent._greenlet.Greenlet._raise_exception()

~/.local/lib/python3.6/site-packages/gevent/_compat.py in reraise(t, value, tb)
     62     def reraise(t, value, tb=None): # pylint:disable=unused-argument
     63         if value.__traceback__ is not tb and tb is not None:
---> 64             raise value.with_traceback(tb)
     65         raise value
     66     def exc_clear():

~/.local/lib/python3.6/site-packages/gevent/_greenlet.cpython-36m-x86_64-linux-gnu.so in gevent._greenlet.Greenlet.run()

~/.local/lib/python3.6/site-packages/pssh/clients/base_pssh.py in _copy_file()
    271         except Exception as ex:
    272             ex.host = host
--> 273             raise ex
    274 
    275     def copy_remote_file(self, remote_file, local_file, recurse=False,

~/.local/lib/python3.6/site-packages/pssh/clients/base_pssh.py in _copy_file()
    268             self._make_ssh_client(host)
    269             return self.host_clients[host].copy_file(local_file, remote_file,
--> 270                                                      recurse=recurse)
    271         except Exception as ex:
    272             ex.host = host

~/.local/lib/python3.6/site-packages/pssh/clients/native/single.py in copy_file()
    520             except (SFTPHandleError, SFTPProtocolError):
    521                 self.mkdir(sftp, destination)
--> 522         self.sftp_put(sftp, local_file, remote_file)
    523         logger.info("Copied local file %s to remote destination %s:%s",
    524                     local_file, self.host, remote_file)

~/.local/lib/python3.6/site-packages/pssh/clients/native/single.py in sftp_put()
    538                 sftp.open, remote_file, f_flags, mode) as remote_fh:
    539             try:
--> 540                 self._sftp_put(remote_fh, local_file)
    541                 # THREAD_POOL.apply(
    542                 #     sftp_put, args=(self.session, remote_fh, local_file))

~/.local/lib/python3.6/site-packages/pssh/clients/native/single.py in _sftp_put()
    525 
    526     def _sftp_put(self, remote_fh, local_file):
--> 527         with open(local_file, 'rb', 2097152) as local_fh:
    528             for data in local_fh:
    529                 eagain_write(remote_fh.write, data, self.session)

OSError: [Errno 24] Too many open files: '/path/to/file/file.ext'
```

__Expected behaviour:__ [What was expected to happen.]

Continue copying until done

__Actual behaviour:__ [What actually happened.]

See traceback above

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]

```sh
$ python3 --version
Python 3.6.8

$ pip3 list parallel-ssh
Package          Version
---------------- ------------
backcall         0.1.0
bcrypt           3.1.7
cffi             1.14.0
cryptography     2.9.2
decorator        4.4.2
gevent           20.5.0
greenlet         0.4.15
ipython          7.14.0
ipython-genutils 0.2.0
jedi             0.17.0
parallel-ssh     1.9.1
paramiko         2.7.1
parso            0.7.0
pexpect          4.8.0
pickleshare      0.7.5
pip              20.1.1
prompt-toolkit   3.0.5
pssh             2.3.1
ptyprocess       0.6.0
pycparser        2.20
Pygments         2.6.1
PyNaCl           1.3.0
PyYAML           5.3.1
setuptools       39.2.0
six              1.14.0
ssh2-python      0.18.0.post1
traitlets        4.3.3
wcwidth          0.1.9
```

**Comment by dyasny** [comment]
Today I tried with `scp_send` instead, got this:

```
Traceback (most recent call last):
  File "/home/centos/.local/lib/python3.6/site-packages/pssh/clients/native/single.py", line 192, in _init
  File "/home/centos/.local/lib/python3.6/site-packages/pssh/clients/native/single.py", line 265, in auth
  File "/home/centos/.local/lib/python3.6/site-packages/pssh/clients/native/single.py", line 235, in _pkey_auth
  File "ssh2/session.pyx", line 175, in ssh2.session.Session.userauth_publickey_fromfile
  File "ssh2/utils.pyx", line 127, in ssh2.utils.handle_error_codes
ssh2.exceptions.FileError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "src/gevent/libev/corecext.pyx", line 1293, in gevent.libev.corecext._syserr_cb
  File "src/gevent/libev/corecext.pyx", line 553, in gevent.libev.corecext.loop._handle_syserr
  File "src/gevent/libev/corecext.pyx", line 561, in gevent.libev.corecext.loop.handle_error
  File "/home/centos/.local/lib/python3.6/site-packages/gevent/hub.py", line 518, in handle_error
  File "/home/centos/.local/lib/python3.6/site-packages/gevent/hub.py", line 540, in handle_system_error
greenlet.error: cannot switch to a different thread
(libev) error creating signal/async pipe: Too many open files
Aborted
```

looks like it's not the copied files but the handlers on gevent greenlets that are the bottleneck?

**Comment by dyasny** [comment]
After digging in a bit, I realise I was most probably hitting #175. The workaround seems to be working. 

I'm monitoring the number of open fds as I copy and it fluctuates around 30-35 instead of running away into the thousands.

**Comment by dyasny** [comment]
working function, if anyone is interested:

```python
def copy_file(file_path, node_list, dest_dir, ssh_auth):
    success = True
    client = ParallelSSHClient(node_list, **ssh_auth)
    filename = file_path.split('/')[-1]
    greenlets = client.scp_send(file_path, dest_dir + '/' + filename)
    out = joinall(greenlets, raise_error=True)
    for item in out:
        if not item.successful():
            success = False
    for single_client in client.host_clients.values(): 
        single_client.disconnect() 
    return success
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and bug report. Yes, this is same issue as #175 - closing this as duplicate.

**Comment by dyasny** [comment]
Thanks, I ended up dropping pssh and simply running ssh via subprocess in parallel. Easy, stable and bugfree. Would be great to try again when things are more stable here
