### ISSUE TITLE
SocketRecvError Mac --> Linux

### ISSUE THREAD

**Issue by DeemOnSecurity** [ParallelSSH/parallel-ssh#218]
### Directions

_Issue tracker is for actionable bug reports, issues with the code and feature requests._
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._
_Remove this section and everything on and above this line._

### Bug reports

__Steps to reproduce:__

1. Example code that produces error.

```python
from pssh.clients.native import ParallelSSHClient as NativeSSHClient

class NativeSSH(NativeSSHClient):

    def run_python(self, command: str, python=-1, *args, **kwargs) -> dict:
        """
        Execute python scripts on a remote machine.

        Any python file can be open(file).read() in to run_python().

        :param command: The raw python to execute.
        :type command: str
        :param python: Version (major) of python to target with the module.
        :type python: int
        :param args: Any bare args passed are ignored.
        :param kwargs: Keyword arguments to pass to ParallelSSHClient's run_command() method.
        :return: Returns a NativeSSHClient dict with the returns from the host set.
        """

        if python == 2:
            command = f"(/usr/bin/env python || /usr/bin/env python2) <<EOF\n \n{command} \nEOF"

        elif python == 3:
            command = f"(/usr/bin/env python3 || /usr/bin/env python) <<EOF\n \n{command} \nEOF"

        else:
            command = f"(/usr/bin/env python3 || /usr/bin/env python || /usr/bin/env python2) <<EOF\n \n{command} \nEOF"

        return self.run_command(command, **kwargs)

class Connection(object):
    """Connection() object helps us neatly handle our host set connections and authentication."""

    def __init__(self, hosts, user, private_key="~/.ssh/id_rsa", port=22):
        """
        Initiate Connection().

        :param hosts: A list of hosts which comprises a host set.
        :type hosts: list
        :param user: The username to authenticate with.
        :type user: str
        :param private_key: Path to whatever the private key is (default: ~/.ssh/id_rsa)
        :type private_key: str
        :param port: Port to connect with over SSH (default: 22)
        :type port: int
        """
        if isinstance(hosts, str):
            hosts = [hosts]
        self.hosts: list = hosts
        self.user: str = user
        self.password: str = ""
        self.private_key: str = private_key
        self.port: int = port

    @property
    def native(self):
        """
        Handle authentication type to use based on what was passed to Connection().

        :return: NativeSSH() object.
        """

        # parallel-ssh gets confused it you pass it a password and a private key, so if we have a key
        # for the host we prefer to pass it. Otherwise we pass the password
        if not self.password:
            return NativeSSH(
                self.hosts, user=self.user, pkey=self.private_key, port=self.port
            )
        else:
            return NativeSSH(
                self.hosts, user=self.user, password=self.password, port=self.port
            )


if __name__ == '__main__':
    connection = Connection(['192.168.122.138', ], 'will')

    output = connection.native.run_command('echo "test"', return_list=True)
    print(list(output[0]['stdout']))
```

2. Stack trace or error messages.
```shell
Traceback (most recent call last):
  File "Project/SSH.py", line 89, in <module>
    print(list(output[0]['stdout']))
  File "/Users/User/PycharmProjects/Project/Project/venv/lib/python3.7/site-packages/pssh/clients/base/single.py", line 242, in read_output_buffer
    for line in output_buffer:
  File "pssh/native/_ssh2.pyx", line 55, in _read_output
  File "ssh2/channel.pyx", line 116, in ssh2.channel.Channel.read
  File "ssh2/channel.pyx", line 144, in ssh2.channel.Channel.read_ex
  File "ssh2/utils.pyx", line 179, in ssh2.utils.handle_error_codes
ssh2.exceptions.SocketRecvError
```
__Expected behaviour:__ [What was expected to happen.]

Expected a return and print of "test"

__Actual behaviour:__ [What actually happened.]

SocketRecvError

__Additional info:__ [Include version of ``ssh2-python`` and/or ``paramiko`` and any other relevant information.]

Machine running pssh: 

```shell
$ uname -a
Darwin Machine 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

```shell
$ python3 --version
Python 3.7.7
```

```shell
$ python3 -m pip freeze
bcrypt==3.2.0
cffi==1.14.2
cryptography==3.1
gevent==20.6.2
greenlet==0.4.16
parallel-ssh==1.13.0
paramiko==2.7.2
pycparser==2.20
PyNaCl==1.4.0
six==1.15.0
ssh-python==0.6.0
ssh2-python==0.19.0
zope.event==4.4
zope.interface==5.1.0
```

Machine(s) tested:

**Ubuntu Server**
```shell
$ uname -a
Linux ubuntuserver 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```shell
$ ssh -V
OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f 31 Mar 2020
```

**Kali Linux Machine**

```shell
$ uname -a
Linux kali 5.7.0-kali3-amd64 #1 SMP Debian 5.7.17-1kali1 (2020-08-26) x86_64 GNU/Linux
```

```shell
$ ssh -V
OpenSSH_8.3p1 Debian-1, OpenSSL 1.1.1g 21 Apr 2020
```

**CentOS Linux 7**
```shell
$ uname -a
Linux CentOS7.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```shell
$ ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips 26 Jan 2017
```

I am curious if this is an SSH library issue on Mac, as we have had issues connecting from a Mac to a FreeBSD machine previously, but were able to do so from a Debian machine.

**Comment by DeemOnSecurity** [comment]
Tested in a docker container and getting the same error. Was there a change made to ssh2 that broke this?

**Comment by DeemOnSecurity** [comment]
Updated OpenSSH to verify this was not the issue. Still NEGRES

**Old**
```shell
OpenSSH_8.1p1, LibreSSL 2.7.3
```

**New**
```shell
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by pkittenis** [comment]
OpenSSH on client side is not used. The client uses embedded `libssh2` via ssh2-python, which got upgraded to `1.9.0` in `0.19.0`.

Did this used to work?

Can you please enable debug output and post it here:

```
import logging
from pssh import logger
from pssh.utils import enable_logger

enable_logger(logger, logging.DEBUG)

<your code>
```

**Comment by DeemOnSecurity** [comment]
Good evening,

 Yes, this did work previously. It even currently works for coworkers. The only change in my environment was updating to MacOS Catalina, but I am unsure of what this may have changed given that my environment is otherwise unchanged and my PyCharm interpreter has full accessibility. 

Here is the output:
```
Make client request for host 192.168.122.138, host in clients: False
Connecting to 192.168.122.138:22
Proceeding with private key file authentication
Authentication completed successfully - setting session to non-blocking mode
Executing command 'echo "test"'
Disconnecting clients
Disconnecting client for host 192.168.122.138
Traceback (most recent call last):
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT/PROJECT/SSH.py", line 91, in <module>
    connection.native.join(output)
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT/venv/lib/python3.7/site-packages/pssh/clients/base/parallel.py", line 339, in join
    finished_cmds = joinall(cmds, raise_error=True, timeout=timeout)
  File "src/gevent/greenlet.py", line 1002, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/greenlet.py", line 1018, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT/venv/lib/python3.7/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT_Slimfactor/venv/lib/python3.7/site-packages/pssh/clients/base/parallel.py", line 359, in _join
    client.wait_finished(channel, timeout=timeout)
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT/venv/lib/python3.7/site-packages/pssh/clients/native/single.py", line 283, in wait_finished
    self._eagain(channel.wait_eof)
  File "/Users/USER/PycharmProjects/PROJECT_Scratches/PROJECT/venv/lib/python3.7/site-packages/pssh/clients/native/single.py", line 294, in _eagain
    wait_select(self.session)
  File "pssh/native/_ssh2.pyx", line 89, in pssh.native._ssh2.wait_select
AttributeError: 'NoneType' object has no attribute 'block_directions'

Process finished with exit code 1
```

**Comment by pkittenis** [comment]
```
    output = connection.native.run_command('echo "test"', return_list=True)
    print(list(output[0]['stdout']))
```

The code needs to keep the client in scope otherwise connections will be terminated. 

The use of @property is letting the client go out of scope in between `run_command` and output being read. Connections are disconnected when client goes out of scope. Once connections are terminated cannot read output.

Change `Connection` class to hold client object as attribute, not via property. Code will run faster too as every call to `connection.native.run_command` is creating new client and new connections, even for same hosts.

```
class Connection(object):
    """Connection() object helps us neatly handle our host set connections and authentication."""

    def __init__(self, hosts, user, private_key="~/.ssh/id_rsa", port=22):
        """
        Initiate Connection().

        :param hosts: A list of hosts which comprises a host set.
        :type hosts: list
        :param user: The username to authenticate with.
        :type user: str
        :param private_key: Path to whatever the private key is (default: ~/.ssh/id_rsa)
        :type private_key: str
        :param port: Port to connect with over SSH (default: 22)
        :type port: int
        """
        if isinstance(hosts, str):
            hosts = [hosts]
        self.hosts: list = hosts
        self.user: str = user
        self.password: str = ""
        self.private_key: str = private_key
        self.port: int = port
        _password = None if self.password == '' else self.password
        self.client = NativeSSH(
                self.hosts, user=self.user, password=_password, pkey=self.private_key, port=self.port)
```

**Comment by DeemOnSecurity** [comment]
That did the trick! Thank you!
