### ISSUE TITLE
The example with "localhost" and "uname" is broken

### ISSUE THREAD

**Issue by PPPW** [ParallelSSH/parallel-ssh#379]
_For general questions please use the [mail group](https://groups.google.com/forum/#!forum/parallel-ssh)._

**Describe the bug**
The example in the README is broken:
```
from pssh.clients import ParallelSSHClient

hosts = ['localhost', 'localhost']
client = ParallelSSHClient(hosts)

output = client.run_command('uname')
```

**To Reproduce**
Run the above example.

**Expected behavior**
The above code runs successfully.

**Actual behaviour**
The above code got exception:
```
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.10/site-packages/pssh/clients/base/single.py", line 204, in _auth_retry
    self.auth()
  File "/home/azureuser/.local/lib/python3.10/site-packages/pssh/clients/base/single.py", line 364, in auth
    return self._identity_auth()
  File "/home/azureuser/.local/lib/python3.10/site-packages/pssh/clients/base/single.py", line 337, in _identity_auth
    raise AuthenticationError("No authentication methods succeeded")
pssh.exceptions.AuthenticationError: No authentication methods succeeded
...
pssh.exceptions.AuthenticationError: ('Authentication error while connecting to %s:%s - %s - retries %s/%s', 'localhost', 22, AuthenticationError('No authentication methods succeeded'), 3, 3)
```

**Additional information**
The issue happens when no auth is needed, e.g., SSH to localhost, or to a host without the need of `-i`. The `ParallelSSHClient`'s constructor takes `identity_auth=False`, however with that, in `/pssh/clients/base/single.py`, it will try to do password auth, which also doesn't apply. This looks like a regression. Could you fix that and support uses cases that auth is not needed? Thank you!

**Comment by christiankotait** [comment]
Same issue. Can you please fix this?

**Comment by comperem** [comment]
hello, agreed. I've experienced this problem for 2 years.

what's the status on this issue?

golly, how can the front-page example not work correctly?

**Comment by pkittenis** [comment]
Using `enable_debug_logger` will show which keys are being used to authenticate.

Eg with no ssh-agent running and no key specified:

```
2025-01-13 00:21:04,808 DEBUG    pssh.clients.base.single Agent auth failed with AgentAuthenticationError('No identities match for user %s', b'xx') continuing with other authentication methods
2025-01-13 00:21:04,809 DEBUG    pssh.clients.base.single Trying to authenticate with identity file /home/zefrer/.ssh/id_rsa
2025-01-13 00:21:04,809 DEBUG    pssh.clients.base.single Authentication with identity file /home/xx/.ssh/id_rsa failed with , continuing with other identities
2025-01-13 00:21:04,809 DEBUG    pssh.clients.base.single Trying to authenticate with identity file /home/zefrer/.ssh/id_ecdsa
2025-01-13 00:21:04,822 INFO     pssh.clients.base.single Authentication succeeded with identity file /home/xx/.ssh/id_ecdsa
2025-01-13 00:21:04,822 DEBUG    pssh.clients.base.single Authentication completed successfully - setting session to non-blocking mode
2025-01-13 00:21:04,848 DEBUG    pssh.clients.base.single Agent auth failed with AgentAuthenticationError('No identities match for user %s', b'xx') continuing with other authentication methods
2025-01-13 00:21:04,849 DEBUG    pssh.clients.base.single Trying to authenticate with identity file id_rsa
2025-01-13 00:21:04,849 DEBUG    pssh.clients.base.single Authentication with identity file id_rsa failed with , continuing with other identities
2025-01-13 00:21:04,849 DEBUG    pssh.clients.base.single Trying to authenticate with identity file /home/zefrer/.ssh/id_ecdsa
2025-01-13 00:21:04,861 INFO     pssh.clients.base.single Authentication succeeded with identity file /home/zefrer/.ssh/id_ecdsa
2025-01-13 00:21:04,861 DEBUG    pssh.clients.base.single Authentication completed successfully - setting session to non-blocking mode
```

Likely the native client lacks support for one of the default keys in https://github.com/ParallelSSH/parallel-ssh/blob/master/pssh/clients/base/single.py#L150-L156 or the SSH server stops allowing new keys after failures.

There is no authentication without a key, all clients use a set of default keys if nothing is provided.

This is also the case for the above.

Either provide a valid key or have one in running agent.
