### ISSUE TITLE
I am getting UnknownHostException

### ISSUE THREAD

**Issue by avinash-mishra** [ParallelSSH/parallel-ssh#84]
I am trying to run some commands on two servers. And while running I am getting following error. 
Please suggest. 

```
Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 179, in _connect
    allow_agent=self.allow_agent)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 295, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 199, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/pool.py", line 325, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 385, in get
    return self.get(block=False)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 375, in get
    return self._raise_exception()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 355, in _raise_exception
    reraise(*self.exc_info)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 179, in _connect
    allow_agent=self.allow_agent)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 295, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 199, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/pool.py", line 325, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 385, in get
    return self.get(block=False)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 375, in get
    return self._raise_exception()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 355, in _raise_exception
    reraise(*self.exc_info)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 179, in _connect
    allow_agent=self.allow_agent)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 295, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/paramiko/client.py", line 199, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/pool.py", line 325, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 385, in get
    return self.get(block=False)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 375, in get
    return self._raise_exception()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/event.py", line 355, in _raise_exception
    reraise(*self.exc_info)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testRunSpiderViaSsh.py", line 9, in <module>
    class testRunSpiderViaSshLogic():
  File "testRunSpiderViaSsh.py", line 11, in testRunSpiderViaSshLogic
    runSpider.runSpider('agoda_kuchikomi.py')
  File "../runSpiderViaSsh.py", line 34, in runSpider
    self.runSpiderAsynchronously(ota)
  File "../runSpiderViaSsh.py", line 42, in runSpiderAsynchronously
    output = client.run_command('pwd', sudo=True)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/pssh_client.py", line 684, in run_command
    self.get_output(cmd, output, encoding=encoding)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/pssh_client.py", line 759, in get_output
    (channel, host, stdout, stderr, stdin) = cmd.get()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/greenlet.py", line 456, in get
    self._raise_exception()
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/greenlet.py", line 159, in _raise_exception
    reraise(*self.exc_info)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/pssh_client.py", line 711, in _exec_command
    agent=self.agent, channel_timeout=self.channel_timeout)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 130, in __init__
    self._connect(self.client, self.host, self.port)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 186, in _connect
    retries=retries+1)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 186, in _connect
    retries=retries+1)
  File "/var/users/ec2-user/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pssh/ssh_client.py", line 189, in _connect
    self.num_retries)
pssh.exceptions.UnknownHostException: ('Unknown host %s - %s - retry %s/%s', '[', 'Name or service not known', 3, 3)
```

**Comment by pkittenis** [comment]
The exception `pssh.exceptions.UnknownHostException: ('Unknown host %s - %s - retry %s/%s', '[', 'Name or service not known', 3, 3)` is showing a host name of `[`, which could not be resolved (`UnknownHostException`). Probably want to check that the host list is valid and that the host names can be resolved.
